Develop
gymshark/go-hasher pull request #5
Opened 2021-02-24 17:22 UTC by mikezange

2021-02-24 18:03 UTC, lushc requested changes
Nice and tidy refactor 👍  just requesting a change to fix `ExampleSha256`

2021-02-25 09:36 UTC, jordanfinners commented on hasher_test.go
> +	fmt.Println(h)
How comes these are in a test file?

2021-02-25 09:45 UTC, mikezange commented on hasher_test.go
> +	fmt.Println(h)
https://blog.golang.org/examples

2021-02-26 11:24 UTC, mikezange commented on hasher_test.go
> -	hash, err := Sha512([]byte("hello"), Hex)
Fixed

2021-02-26 11:25 UTC, lushc approved these changes

2021-02-26 12:38 UTC, jordanfinners commented on hasher_test.go
> +	fmt.Println(h)
Ooo not seen that before, good to know

2021-02-26 13:16 UTC, lushc approved these changes

2021-02-26 14:47 UTC, merged